### ISSUE TITLE
Software does not build after upgrade of opentk packages to verion 4.9.1

### ISSUE THREAD

**Issue by AlexandreAlison** [opentk/GLControl#41]
Hello,

I updated our OpenTk packages to 4.9.1 in our solution and I have this issue.
![image](https://github.com/user-attachments/assets/289d9126-5a50-43a8-b512-d40a238080f9)

now the opentk dlls are signed (could be from version 9). 
![image](https://github.com/user-attachments/assets/ecc6feff-fcc1-478c-b935-2265cb378f29)

So my issue could to be related to the OpenTK.GLControl nuget package (v4.0.1): it is targeting unsigned dlls.
![image](https://github.com/user-attachments/assets/749b77c2-fd78-4641-87e6-c7ed6c4c88a6)

I am guessing right and a new  OpenTK.GLControl is needed? could you please help me?

Thanks.

**Comment by NogginBops** [comment]
Yeah it does seem reasonable that a new `OpenTK.GLControl` is needed.
I'll see if I can upgrade it later today.

**Comment by NogginBops** [comment]
I figured out the issue. It was an OpenTK issue.
I've opened a new issue here: https://github.com/opentk/opentk/issues/1782

**Comment by NogginBops** [comment]
@AlexandreAlison I've just released `OpenTK 4.9.3` which should hopefully solve this issue at long last. You can close this issue if `4.9.3` solves your problem.

**Comment by AlexandreAlison** [comment]
Sorry for the delay: it took a bit of time until our Azure Devops feed let me get the packages from nuget.org.

I cleaned and rebuilt the whole application but I still have the issue:
![image](https://github.com/user-attachments/assets/155e693b-0754-4eab-a6cd-406447265b53)

![image](https://github.com/user-attachments/assets/1bc4bc63-bd52-4c3d-8706-9996378db54c)

**Comment by AlexandreAlison** [comment]
I am trying to isolate this part of the code. I will test then and if I have still the issue I will post the code here.

**Comment by AlexandreAlison** [comment]
here it is: [CIELab3D.zip](https://github.com/user-attachments/files/18091028/CIELab3D.zip)

using opentk version 4.8.2 it builds. 

Version 4.9.3
![image](https://github.com/user-attachments/assets/d042d405-f3c8-46d6-9753-617b6d6a3c02)

**Comment by NogginBops** [comment]
Thanks for the repro, will try and find out what the issue is.

**Comment by NogginBops** [comment]
Fixed with #42

**Comment by AlexandreAlison** [comment]
I updated all the OpenTK package to the latest version and it built.

Thanks  a lot.
